//
// Generated file, do not edit! Created by nedtool 5.0 from vehicleAnimatorPkt.msg.
//

#ifndef __NCS_VEHICLEANIMATORPKT_M_H
#define __NCS_VEHICLEANIMATORPKT_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


namespace ncs {

/**
 * Class generated from <tt>vehicleAnimatorPkt.msg:21</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet vehcileAnimatorPkt
 * {
 *     double x;
 *     double y;
 *     double theta;
 * }
 * </pre>
 */
class vehcileAnimatorPkt : public ::omnetpp::cPacket
{
  protected:
    double x;
    double y;
    double theta;

  private:
    void copy(const vehcileAnimatorPkt& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const vehcileAnimatorPkt&);

  public:
    vehcileAnimatorPkt(const char *name=nullptr, int kind=0);
    vehcileAnimatorPkt(const vehcileAnimatorPkt& other);
    virtual ~vehcileAnimatorPkt();
    vehcileAnimatorPkt& operator=(const vehcileAnimatorPkt& other);
    virtual vehcileAnimatorPkt *dup() const {return new vehcileAnimatorPkt(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
    virtual double getX() const;
    virtual void setX(double x);
    virtual double getY() const;
    virtual void setY(double y);
    virtual double getTheta() const;
    virtual void setTheta(double theta);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const vehcileAnimatorPkt& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, vehcileAnimatorPkt& obj) {obj.parsimUnpack(b);}

} // namespace ncs

#endif // ifndef __NCS_VEHICLEANIMATORPKT_M_H

