`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: TUM - HCS
// Engineer: M. Khaled
//
// This file was automatically generated by the tool Imhotep.
// 
// Create Date: #$DATES$#
// Module Name: bddWrapper as Verilog code
// Project Name: Symbolic Controller implementation
// Target Devices: FPGA
//
// Additional Comments: refer to HCS website for additional information and toos:
//
// 	http://www.hcs.ei.tum.de
//
//////////////////////////////////////////////////////////////////////////////////


module bddWrapper(
#$MODULE_INPUT_PORTS$#
#$MODULE_OUTPUT_PORTS$#
    );
    
#$ASSIGN_OUTPUT_FUNCTIONS$#

endmodule

