--////////////////////////////////////////////////////////////////////////////////
-- Company: TUM - HCS
-- Engineer: M. Khaled
--
-- This file was automatically generated by the tool Imhotep.
-- 
-- Create Date: #$DATES$#
-- Module Name: bddWrapper as Verilog code
-- Project Name: Symbolic Controller implementation
-- Target Devices: FPGA
--
-- Additional Comments: refer to HCS website for additional information and toos:
--
-- 	http://www.hcs.ei.tum.de
--
--////////////////////////////////////////////////////////////////////////////////

library ieee;
use ieee.std_logic_1164.all;


entity BDDWrapper_entity is
port(	
#$ENTITY_INPUT_PORTS$#
#$ENTITY_OUTPUT_PORTS$#
);
end BDDWrapper_entity;  


architecture BDDWrapper_behavioral of BDDWrapper_entity is 
begin 
#$BEHAVIORAL_OUTPUT_FUNCTIONS$#
end BDDWrapper_behavioral;
